spring:
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mailgun.org
    username: dev-ttlabz@sandbox477111e0780d401c9cb64ec06754f12a.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

pombo:
  rate-limit:
    ip:
      apply-limit: false