spring:
  application:
    name: Pombo

  data:
    redis:
      host: "redis-15541.c336.samerica-east1-1.gce.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 15541
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://db.thaiidrqkdmjsdnfrnsd.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle_timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    port: 587
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: jaragua.lmq.cloudamqp.com
    password: ${RABBIT_PASSWORD}
    username: rbbafvlm
    ssl:
      enabled: true
    virtual-host: rbbafvlm
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max_interval: 10000ms
          max_attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET}

pombo:
  email:
    from: mail@ttlabz.com
    verification:
      expiry-hours: 24

    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1"
    - "::1"
    - "10.0.0.0/8"      # Internal GCP network
    - "172.16.0.0/12"   # Private network range
    - "192.168.0.0/16"  # Private network range
    - "0.0.0.0/0"       # TEMPORARY TEST: Trust all

supabase:
  url: "https://thaiidrqkdmjsdnfrnsd.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}

firebase:
  credentials-path: "classpath:firebase-credentials/pombo-firebase-adminsdk.json"