spring:
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.mailgun.org
    username: dev-ttlabz@sandbox477111e0780d401c9cb64ec06754f12a.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

pombo:
  email:
    url: "https://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true